version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASS=dev_password
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db


volumes:
  dev-db-data:

